; GuppOS Ship Manager
;--------------------------------------
; Recompile PB to apply config changes
; Setting a group name to ALL will cause the script to act upon all blocks of type on the grid

[GuppOS.General]
;Log everything
LogAll=false
;Tag to identiy GuppOS LCDs
LCDTag=<GOSLCD>
;Tag to ignore block
IgnoreTag=<I>

[GuppOS.PowerManager]
;Enable manager
PowerManagerEnabled=true
;Group names
MainBatteryGroup=Main Batteries
BackupBatteryGroup=Backup Batteries
MainReactorGroup=ALL
;Power percentage to enable reactors
LowPowerLevel=25
;Power percentage to disable reactors
HighPowerLevel=90

[GuppOS.Tanks]
;Group names
MainFuelTankGroup=Fuel Tanks
MainAirTankGroup=Air Tanks

[GuppOS.Propulsion]
;Group names
EpsteinDriveGroup=Main Drives
RCSGroup=RCS Drives
GyroGroup=Gyros

[GuppOS.LifeSupport]
;Group names
VentGroup=ALL
GravGenGroup=ALL

[GuppOS.Lighting]
;Group names
LightGroup=ALL
;Basic light tags
NavLightTag=*NAV*

[GuppOS.Doors]
;Enable manager
DoorManagerEnabled=true
;Group names
DoorGroup=ALL
;Time for doors to remain open (integer times 100 ticks)
DoorOpenLength=6

[GuppOS.Connectors]
ConnectorGroup=ALL

;--------------------------------------
;Posture configs:
[GuppOS.Posture.Cruise]
;Power settings
; Override power manager battery settings
OverrideBatteries=false
; Override power manager reactor settings
OverrideReactors=false
;Tank settings
StockpileFuel=false
StockpileAir=false
;Propulsion settings
; Epstein drive mode
EpsteinsEnabled=true
; RCS thruster mode
RCSEnabled=true
; Gyroscope mode
GyrosEnabled=true
;Life support modes
; Vent mode
PressurizeVents=true
; Gravity generator mode
GravEnabled=true
;Lighting
; Enable/disable navigation lighting
NavLightsOn=true
; Sets lights = tag:enabled:RGBcolour (light setting # does not matter as long as there are no duplicates)
LightSetting1=*IN*:true:255,255,255
LightSetting2=*OUT*:true:255,255,255
LightSetting3=*DOCK*:false
;Connectors
; Sets connectors = tag:enabled
ConSetting1=|Dockers|:false
ConSetting2=|Docks|:true

[GuppOS.Posture.Maneuver]
;Posture of this name's settings are inherited
Inherits=Cruise
;Propulsion settings
; Epstein drive mode
EpsteinsEnabled=false

[GuppOS.Posture.StealthCruise]
;Posture of this name's settings are inherited
Inherits=Cruise
;Lighting
; Enable/disable navigation lighting
NavLightsOn=false
; Sets lights = tag:enabled:RGBcolour (light setting # does not matter as long as there are no duplicates)
LightSetting1=*IN*:true:200,200,255
LightSetting2=*OUT*:false

[GuppOS.Posture.StealthManeuver]
;Posture of this name's settings are inherited
Inherits=Maneuver
;Lighting
; Enable/disable navigation lighting
NavLightsOn=false
; Sets lights = tag:enabled:RGBcolour (light setting # does not matter as long as there are no duplicates)
LightSetting1=*IN*:true:200,200,255
LightSetting2=*OUT*:false

[GuppOS.Posture.Combat]
;Posture of this name's settings are inherited
Inherits=Cruise
;Power settings
; Override power manager battery settings
OverrideBatteries=true
;  Sets main battery mode
MainBatteryMode=Auto
;  Sets backup battery mode
BackupBatteryMode=Auto
; Override power manager reactor settings
OverrideReactors=true
;  Sets main reactors on/off
MainReactorStatus=true
;Life support modes
; Vent mode
PressurizeVents=false
; Gravity generator mode
GravEnabled=false
;Lighting
; Enable/disable navigation lighting
NavLightsOn=false
; Sets lights = tag:enabled:RGBcolour (light setting # does not matter as long as there are no duplicates)
LightSetting1=*IN*:true:255,0,0
LightSetting2=*OUT*:false

[GuppOS.Posture.Docking]
;Posture of this name's settings are inherited
Inherits=Maneuver
;Lighting
; Sets lights = tag:enabled:RGBcolour (light setting # does not matter as long as there are no duplicates)
LightSetting1=*DOCK*:true:255,255,255
;Connectors
; Sets connectors = tag:enabled
ConSetting1=|Dockers|:true

[GuppOS.Posture.Docked]
;Posture of this name's settings are inherited
Inherits=Docking
;Power settings
; Override power manager battery settings
OverrideBatteries=true
;  Sets main battery mode
MainBatteryMode=Recharge
;  Sets backup battery mode
BackupBatteryMode=Recharge
; Override power manager reactor settings
OverrideReactors=true
;  Sets main reactors on/off
MainReactorStatus=false
;Tank settings
StockpileFuel=true
StockpileAir=true
;Propulsion settings
; Epstein drive mode
EpsteinsEnabled=false
; RCS thruster mode
RCSEnabled=false
; Gyroscope mode
GyrosEnabled=false
;Life support modes
; Gravity generator mode
GravEnabled=false

---